# Generated by Django 4.2.2 on 2023-06-30 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='idCategoria', primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id_noticia', models.AutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('img_hero', models.ImageField(blank=True, null=True, upload_to='hero')),
                ('bajada_titulo', models.CharField(max_length=100)),
                ('contenido', models.CharField(max_length=1000)),
                ('subtitulo', models.CharField(max_length=100)),
                ('img_noticias', models.ImageField(blank=True, null=True, upload_to='noticias')),
                ('contenido2', models.CharField(max_length=1000)),
                ('subtitulo2', models.CharField(max_length=100)),
                ('img_noticias2', models.ImageField(blank=True, null=True, upload_to='noticias2')),
                ('contenido3', models.CharField(max_length=1000)),
                ('id_categoria', models.ForeignKey(db_column='idCategoria', on_delete=django.db.models.deletion.CASCADE, to='noticias.categoria')),
            ],
        ),
    ]
