# Generated by Django 4.2.2 on 2023-06-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='contenido',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='contenido3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo2',
            field=models.CharField(max_length=100),
        ),
    ]
