# Generated by Django 4.2.2 on 2023-06-24 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_alter_noticia_contenido_alter_noticia_contenido2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img_hero',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img_noticias',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img_noticias2',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
