# Generated by Django 4.2.2 on 2023-06-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_noticia_img_hero_alter_noticia_img_noticias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='img_hero',
            field=models.ImageField(blank=True, null=True, upload_to='hero'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img_noticias',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='img_noticias2',
            field=models.ImageField(blank=True, null=True, upload_to='noticias2'),
        ),
    ]
