# Generated by Django 4.2.2 on 2023-07-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_alter_equipo_img_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_usuario',
        ),
        migrations.AlterField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
